import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ahosan-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {<Navbar></Navbar>}
          <div className="">
          {children}
          </div>
          <footer className="bg-blue-900 px-6 py-4 flex gap-x-4 text-white">
            This is my footer
          </footer>
        </body>
    </html>
  );
}
